routes/web.php
<?php


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

#Route::get('/', function () { return view('welcome'); });

/* Front End */
Route::get('/','HomeController@index')->name('main');

Route::get('person','PersonController@index')->name('person');
Route::get('report','ReportController@index')->name('report');
Route::get('resolution','ResolController@index')->name('resolution');

// Back End
Route::get('backoffice','BackofficeController@index')->name('backoffice');

Route::get('committee','BackofficeController@committee')->name('committee');

Route::get('committee/new','BackofficeController@frmPerson')->name('addPerson');
Route::get('committee/store','PersonController@store')->name('storePerson');
Route::resource('/FrmEditPerson','PersonController');
Route::resource('/manage_person', 'PersonController');


Route::get('secretary','BackofficeController@secretary')->name('secretary');

Route::get('content','BackofficeController@content')->name('content');
Route::get('content/new','BackofficeController@frmContent')->name('addContent');
Route::resource('/manage_content', 'ContentController');
Route::resource('/frmEditContent','ContentController');
Route::resource('/editContent','ContentController');

Route::get('meeting','BackofficeController@meeting')->name('meeting');







####test
Route::get('/uploadfile','UploadFileController@index');
Route::post('/uploadfile','UploadFileController@showUploadFile');
####test

resources/views/backend/content.blade.php
@extends('layout.master_backend')

@section('contentBackoffice')
<!-- DataTables Example -->
<div class="card mb-3 main_font">
    <div class="card-header"><i class="fas fa-table"></i>{{ $topicPage }}</div>
    <div class="card-body">
        <div class="table-responsive">
<div align="right" class="mb-2">
    <a href="{{ route('addContent') }}" class="btn btn-success btn-x active" role="button" aria-pressed="true">เพิ่มรายการ</a>
    <a href="#" class="btn btn-primary btn-x" role="button" aria-pressed="true">บันทึกข้อมูล</a>
    <a href="#" class="btn btn-secondary btn-x" role="button" aria-pressed="true">ลบรายการ</a>    
</div>
        
<table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>TOPIC</th>
            <th>ภาพหน้าปก</th>        
            <th>EDIT</th>
            <th>DELETE</th>
            <th>Last Update</th>            
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>ชื่อ-นามสกุล</th>
            <th>ภาพหน้าปก</th>            
            <th>EDIT</th>
            <th>DELETE</th>
            <th>Last Update</th>   
        </tr>
    </tfoot>
    <tbody>
    @foreach ($DataContent as $arrDataContent )            
        <tr>
            <td>
                {{ $arrDataContent->ContentName}}                
            </td>
            <td>
                -
            </td>            
            <td><a href="{{ url('frmEditContent/'.$arrDataContent->ContentID.'/edit') }}" class="btn btn-link">edit</a></td>
            <td>del</td>
            <td>{{ $arrDataContent->updated_at}}</td>            
        </tr>                
    @endforeach        
    </tbody>        
</table>  

        </div>
    </div>    
</div>

@endsection

resources/views/backend/frm_content.blade.php
@extends('layout.master_backend')

@section('contentBackoffice')
<!-- DataTables Example -->
<div class="card mb-3 main_font">
    <div class="card-header"><i class="fas fa-table"></i>{{ $topicPage }}</div>
    <div class="card-body">
        <div class="table-responsive">


<form  method="POST" action="{{ route('manage_content.store') }}" enctype="multipart/form-data">
  @csrf  
<!-- ข้อมูล ข่าว -->    
<div class="card">    
    <div class="card-body">

<!-- TOPIC CATEGORY -->
<div class="form-group">            
    <select class="form-control" name="txt_CategoruID" id="txt_CategoruID" required="required">
        <option value="">:: เลือกหมวดหมู่รายการ ::</option>        
        @foreach ($category as $arrCategory )
            <option value="{{ $arrCategory->CategoryID }}" > {{ $arrCategory->CategoryName }}</option>            
        @endforeach     
    </select>            
</div>

<!-- TOPIC -->
<div class="form-group">
    <div class="form-label-group">        
        <input type="text" name="txt_ContentName" id="txt_ContentName" class="form-control" placeholder="หัวข้อรายการ"  required="required">
        <label for="txt_ContentName">หัวข้อรายการ</label>
    </div>
</div>

<!-- DETAIL -->
<div class="form-group">
    <div class="form-label-group">       
        <div>รายละเอียดรายการ</div>
        <textarea rows="4", cols="54" id="txt_ContentDetail" name="txt_ContentDetail" ></textarea>        
    </div>
</div>


<!-- PICTURE -->
<div class="form-group">
    <label for="">ภาพหน้าปก</label>
    <input type="file" class="form-control-file" name="txt_ContentPic" id="txt_ContentPic" >        
    เลือกกรณีต้องการแสดงภาพหน้าปก -> <input type="checkbox" name="chkIcon" id="chkIcon" value="yes" >
</div>

{{-- ATTECH FILE --}}
<div class="card mt-1">  
    <div class="card-body">

<div>จัดการข้อมูลเอกสารแนบ</div>
<!-- PICTURE -->
<div class="form-group">
    <label for="txt_ContentLink">แนบไฟล์</label>
    <input type="file" class="form-control-file" name="txt_ContentLink" id="txt_ContentLink" >            
</div>

<!-- LINK URL -->
<div class="form-group">
    <div class="form-label-group">        
        <input type="text" name="txt_ContentLinkURL" id="txt_ContentLinkURL" class="form-control" placeholder="Link ข้อมูล">
        <label for="txt_ContentLinkURL">Link ข้อมูล</label>
    </div>
</div>

<!-- EXT LINK -->
<div class="form-group">
    <div class="form-label-group">        
        <input type="checkbox" name="chkEXTLink" id="chkEXTLink" value="accept" >
        <label for="chkEXTLink"> ติ๊กเลื่อก เพื่อลิงค์ไปที่ url ตามด้านบน โดยตรง</label>       
    </div>
</div>

    </div>
</div>
{{-- ATTECH FILE --}}

    </div> <!--card body-->
</div> <!--card-->

<!-- ตั้งค่า ข้อมูล -->    
<div class="card mt-1">    
    <div class="card-body">

<!-- CONTENT HILIGHT -->
<div class="form-group">
    <div class="form-label-group">        
        ตั้งเป็นหัวข้อ Hilight  -> <input type="checkbox" name="chkHilight" value="yes" id="chkHilight" >         
    </div>
</div>

<!-- CONTENT YEAR -->
<div class="form-group">
    <label for="txt_ContentYear" style="color:red;">กรณีรายงานประชุมโปรดระบุปี </label>
    <select class="form-control" name="txt_ContentYear" id="txt_ContentYear">
        <option value="">:: เลือกปีของเนื้อหา ::</option>        
        @foreach ($year as $arrYear )
            <option value="{{ $arrYear->id }}"> 
                {{ $arrYear->ContentYear }}
            </option>            
        @endforeach     
    </select>    
</div>

<!-- Content Status -->
<div class="form-group mt-3">     
    <label for="txt_ContentStatus">เลือกสถานะรายการ</label>   
    <select class="form-control" name="txt_ContentStatus" id="txt_ContentStatus" required="required">
        <option value="">:: เลือกสถานะรายการ ::</option>        
        <option value="on" selected > ONLINE</option>
        <option value="off"> OFFLINE</option>        
    </select>            
</div>

    </div> <!--card body-->
</div> <!--card-->

<div align="right" class="mt-1">        
    <button type="submit" class="btn btn-primary btn-x">บันทึกข้อมูล</button>
    <a href="#" class="btn btn-secondary btn-x" role="button" aria-pressed="true">ยกเลิก</a>    
</div>

</form>

        </div>
    </div>    
</div>

@endsection

resources/views/backend/frm_content_edit.blade.php
@extends('layout.master_backend')

@section('contentBackoffice')
<!-- DataTables Example -->
<div class="card mb-3 main_font">
    <div class="card-header"><i class="fas fa-table"></i>{{ $topicPage }}</div>
    <div class="card-body">
        <div class="table-responsive">

@if( session('alert'))
<div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>{{ session('alert')}}</strong>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
    </button>
</div>
@endif

<form  method="POST" action="{{ url('editContent/'.$id) }}" enctype="multipart/form-data">
  @csrf  
  {{ method_field('PATCH') }}
<!-- ข้อมูล ข่าว -->    
<div class="card">    
    <div class="card-body">

<input type="hidden" name="txt_ContentID" value="{{ $id }}" >
@foreach ($content as $arrContent)
<!-- TOPIC CATEGORY -->
<div class="form-group">      
    <select class="form-control" name="txt_CategoruID" id="txt_CategoruID" required="required">
        <option value="">:: เลือกหมวดหมู่รายการ ::</option>        
        @foreach ($category as $arrCategory )
            <option value="{{ $arrCategory->CategoryID }}" {{ $arrCategory->CategoryID==$arrContent->CategoryID ? 'selected="selected"' : '' }} > 
                {{ $arrCategory->CategoryName }}
            </option>            
        @endforeach     
    </select>            
</div>

<!-- TOPIC -->
<div class="form-group">
    <div class="form-label-group">        
        <input type="text" name="txt_ContentName" id="txt_ContentName" value="{{ $arrContent->ContentName }}" class="form-control" placeholder="หัวข้อรายการ"  required="required">
        <label for="txt_ContentName">หัวข้อรายการ</label>
    </div>
</div>

<!-- DETAIL -->
<div class="form-group">
    <div class="form-label-group">       
        <div>รายละเอียดรายการ</div>
        <textarea rows="4", cols="54" id="txt_ContentDetail" name="txt_ContentDetail" >{{ $arrContent->ContentDetail }}</textarea>        
    </div>
</div>


<!-- PICTURE -->
<div class="form-group">
        <label for="">ภาพหน้าปก</label>
        <input type="file" class="form-control-file" name="txt_ContentPic" id="txt_ContentPic" >        
        เลือกกรณีต้องการแสดงภาพหน้าปก -> <input type="checkbox" name="chkIcon" id="chkIcon" value="yes" {{ $arrContent->ContentIcon=="yes" ? 'checked' : '' }} >
</div>

{{-- ATTECH FILE --}}
<div class="card mt-1">  
        <div class="card-body">
    
    <div>จัดการข้อมูลเอกสารแนบ</div>
    <!-- PICTURE -->
    <div class="form-group">
        <label for="txt_ContentLink">แนบไฟล์</label>
        <input type="file" class="form-control-file" name="txt_ContentLink" id="txt_ContentLink" >            
    </div>
    
    <!-- LINK URL -->
    <div class="form-group">
        <div class="form-label-group">        
            <input type="text" name="txt_ContentLinkURL" id="txt_ContentLinkURL" value="{{ $arrContent->ContentLinkURL }}" class="form-control" placeholder="Link ข้อมูล">
            <label for="txt_ContentLinkURL">Link ข้อมูล</label>
        </div>
    </div>
    
    <!-- EXT LINK -->
    <div class="form-group">
        <div class="form-label-group">        
            <input type="checkbox" name="chkEXTLink" id="chkEXTLink" value="accept" {{ $arrContent->ContentEXTLink=="accept" ? 'checked' : '' }} >
            <label for="chkEXTLink"> ติ๊กเลื่อก เพื่อลิงค์ไปที่ url ตามด้านบน โดยตรง</label>       
        </div>
    </div>
    
        </div>
    </div>
    {{-- ATTECH FILE --}}

    </div> <!--card body-->
</div> <!--card-->

<!-- ตั้งค่า ข้อมูล -->    
<div class="card mt-1">    
    <div class="card-body">

<!-- CONTENT HILIGHT -->
<div class="form-group">
    <div class="form-label-group">        
        ตั้งเป็นหัวข้อ Hilight  -> <input type="checkbox" name="chkHilight" value="yes" id="chkHilight" {{ $arrContent->ContentHilight=="yes" ? 'checked' : '' }} >         
    </div>
</div>

<!-- CONTENT YEAR -->
<div class="form-group">
    <label for="txt_ContentYear" style="color:red;">กรณีรายงานประชุมโปรดระบุปี </label>
    <select class="form-control" name="txt_ContentYear" id="txt_ContentYear">
        <option value="">:: เลือกปีของเนื้อหา ::</option>        
        @foreach ($year as $arrYear )
            <option value="{{ $arrYear->id }}" {{ $arrYear->ContentYear==$arrContent->ContentYear ? 'selected="selected"' : '' }} > 
                {{ $arrYear->ContentYear }}
            </option>            
        @endforeach     
    </select>    
</div>

<!-- Content Status -->
<div class="form-group mt-3">     
    <label for="">เลือกสถานะรายการ</label>   
    <select class="form-control" name="txt_ContentStatus" id="txt_ContentStatus" required="required">    
        <option value="">:: เลือกสถานะรายการ ::</option>        
        <option value="on" {{ $arrContent->ContentStatus=="on" ? 'selected' : '' }} > ONLINE</option>
        <option value="off" {{ $arrContent->ContentStatus=="off" ? 'selected' : '' }}> OFFLINE</option>        
    </select>            
</div>    
@endforeach    

    </div> <!--card body-->
</div> <!--card-->

<div align="right" class="mt-1">        
    <button type="submit" class="btn btn-primary btn-x">บันทึกข้อมูล</button>
    <a href="#" class="btn btn-secondary btn-x" role="button" aria-pressed="true">ยกเลิก</a>    
</div>

</form>

        </div>
    </div>    
</div>

@endsection

resources/views/backend/frm_person.blade.php
@extends('layout.master_backend')

@section('contentBackoffice')
<!-- DataTables Example -->
<div class="card mb-3 main_font">
    <div class="card-header"><i class="fas fa-table"></i>{{ $topicPage }}</div>
    <div class="card-body">
        <div class="table-responsive">


<form  method="POST" action="{{ route('manage_person.store') }}" enctype="multipart/form-data">
  @csrf  
<!-- ข้อมูลส่วนตัว -->    
<div class="card">    
    <div class="card-body">
<div>ข้อมูลส่วนตัว</div>

<!-- title name -->
<div class="form-group mt-3">        
    <select class="form-control" name="txt_title_id">
        <option value="">:: เลือกคำนำหน้า ::</option>
        @foreach ($title_name as $arrTitleName)
            <option value="{{ $arrTitleName->title_id }}">{{ $arrTitleName->title_name_th }}</option>
        @endforeach
    </select>            
</div>   

<!-- name TH -->
<div class="form-group">
<div class="form-row col-md-12">
    <div class="col-md-6">
        <div class="form-label-group">
            <input type="text" name="txt_fname_th" id="firstName_th" class="form-control" placeholder="ระบุชื่อ (ภาษาไทย)"  autofocus="autofocus" required="required">
            <label for="firstName_th">ระบุชื่อ (ภาษาไทย)</label>
        </div>
    </div>
    <div class="col-md-6">
        <div class="form-label-group">
            <input type="text" name="txt_lname_th" id="lastName_th" class="form-control" placeholder="ระบุนามสกุล (ภาษาไทย)" required="required">
            <label for="lastName_th">ระบุนามสกุล (ภาษาไทย)</label>
        </div>
    </div>
</div>
</div>

<!-- IDcard -->
<div class="form-group">
    <div class="form-label-group">
        <input type="text" name="txt_id_card" id="txt_id_card" class="form-control" placeholder="Email address" >
        <label for="txt_id_card">รหัสบัตรประจำตัวประชาชน</label>
    </div>
</div>

<!-- posAcad -->
<div class="form-group mt-3">        
    <select class="form-control" name="txt_posAcad">
        <option value="">:: เลือกตำแหน่งทางวิชาการ ::</option>
        @foreach ($posAcad as $arrPosAcad)
            <option value="{{ $arrPosAcad->pos_acad_id }}">{{ $arrPosAcad->pos_acad_name_th }}</option>
        @endforeach
    </select>            
</div>

<!-- posExec -->
<div class="form-group mt-3">        
    <select class="form-control" name="txt_posExec">
        <option value="">:: เลือกตำแหน่งทางบริหาร ::</option>
        @foreach ($posExec as $arrPosExec)
            <option value="{{ $arrPosExec->pos_exec_id }}">{{ $arrPosExec->pos_exec_name_th }}</option>
        @endforeach
    </select>            
</div>

<!-- PICTURE -->
<div class="form-group">
        <label for="">ภาพหน้าปก</label>
        <input type="file" class="form-control-file" name="txt_person_picture" id="txt_person_picture" >        
    </div>

    </div> <!--card body-->
</div> <!--card-->

<!-- ข้อมูลการติดต่อ -->    
<div class="card mt-1">    
    <div class="card-body">
<div>ข้อมูลที่อยู่</div>

<!-- ADDRESS -->
<div class="form-group mt-3">        
    <div class="col-md-12">
        <div class="form-label-group">
            <input type="text" name="txt_addNum" id="txt_addNum" class="form-control" placeholder="ที่อยู่เลขที่" autofocus="autofocus">
            <label for="txt_addNum">ที่อยู่เลขที่</label>
        </div>
    </div>              
</div>   

<!-- PROVINCE AMPHUR DISTRICT -->
<div class="form-group">
<div class="form-row col-md-12">
    <div class="col-md-4">
        <div class="form-label-group">
            <input type="text" name="txt_addTombol" id="txt_addTombol" class="form-control" placeholder="ระบุตำบล" autofocus="autofocus">
            <label for="txt_addTombol">ระบุตำบล</label>
        </div>
    </div> 

    <div class="col-md-4">
        <div class="form-label-group">
            <input type="text" name="txt_addAmphur" id="txt_addAmphur" class="form-control" placeholder="ระบุอำเภอ" autofocus="autofocus">
            <label for="txt_addAmphur">ระบุอำเภอ</label>
        </div>
    </div> 
    
    <div class="col-md-4">
    <select class="form-control" name="txt_province">
        <option value="">:: เลือกจังหวัด ::</option>
        @foreach ($province as $arrProvince)
            <option value="{{ $arrProvince->province_id }}">{{ $arrProvince->province_name }}</option>
        @endforeach
    </select> 
    </div>   
</div>
</div>

<!-- ZIPCODE MOBILE TEL -->
<div class="form-group">
<div class="form-row col-md-12">
    <div class="col-md-4">
        <div class="form-label-group">
            <input type="text" name="txt_addZipcode" id="txt_addZipcode" class="form-control" placeholder="ระบุรหัสไปรษณีย์" autofocus="autofocus">
            <label for="txt_addZipcode">ระบุรหัสไปรษณีย์</label>
        </div>
    </div> 

    <div class="col-md-4">
        <div class="form-label-group">
            <input type="text" name="txt_tel" id="txt_tel" class="form-control" placeholder="หมายเลขโทรศัพท์" autofocus="autofocus">
            <label for="txt_tel">หมายเลขโทรศัพท์</label>
        </div>
    </div>   

    <div class="col-md-4">
        <div class="form-label-group">
            <input type="text" name="txt_mobile" id="txt_mobile" class="form-control" placeholder="หมายเลขโทรศัพท์เคลื่อนที่" autofocus="autofocus">
            <label for="txt_mobile">หมายเลขโทรศัพท์เคลื่อนที่</label>
        </div>
    </div>         
</div>
</div>

    </div> <!--card body-->
</div> <!--card-->

<!-- ข้อมูลการดำรงตำแหน่ง -->    
<div class="card mt-1">    
    <div class="card-body">
<div>ข้อมูลการดำรงตำแหน่ง</div>

<!-- POSITION COUNCIL -->
<div class="form-group mt-3">        
    <select class="form-control" name="txt_posCounc" required="required">
        <option value="">:: เลือกตำแหน่งในสภามหาวิทยาลัย ::</option>
        @foreach ($posCouncil as $arrPoscouncil)
            <option value="{{ $arrPoscouncil->pos_counc_id }}">{{ $arrPoscouncil->pos_counc_name_th }}</option>
        @endforeach
    </select>            
</div>   

<!-- DELEGATE YEAR -->
<div class="form-group">
    <div class="form-label-group">
        <input type="text" name="txt_delegate_year" id="txt_delegate_year" class="form-control" placeholder="ปีที่รับตำแหน่ง" >
        <label for="txt_delegate_year">ปีที่รับตำแหน่ง</label>
    </div>
</div>

<!-- PERSON STATUS -->
<div class="form-group mt-3">    
    <label for="txt_personStatus">สถานะการดำรงตำแหน่ง</label>    
    <select class="form-control" name="txt_personStatus" id="txt_personStatus" required="required">
        <option value="">:: เลือกสถานะ ::</option>        
        <option value="on" > ดำรงตำแหน่ง</option>
        <option value="out"> หมดวาระ</option>        
    </select>            
</div>


    </div> <!--card body-->
</div> <!--card-->


<div align="right" class="mt-1">        
    <button type="submit" class="btn btn-primary btn-x">บันทึกข้อมูล</button>
    <a href="#" class="btn btn-secondary btn-x" role="button" aria-pressed="true">ยกเลิก</a>    
</div>

</form>

        </div>
    </div>    
</div>

@endsection

resources/views/backend/index.blade.php
@extends('layout.master_backend')

@section('contentBackoffice')
{{-- MAIN Backoffice --}}
<div class="col-12 main_font">
    <div class="card">
        <div class="card-header card_bg_topic">USER MANAGEMENT</div>
        <div class="card-body">           
        {{-- CONTENT --}}
        <div class="row">
            <div class="col-4">
                    <img class="card-img-top mt-2" src="http://placehold.it/380x180" alt="">
            </div>
            <div class="col-8">
                {{-- NAME --}}
                <div class="row mt-2">
                    <div class="col-3"><b>NAME : </b></div>
                    <div class="col-9">THITINAN PHUPHANT</div>
                </div>{{-- NAME --}}

                {{-- USER NAME --}}
                <div class="row mt-2">
                    <div class="col-3"><b>USER NAME : </b></div>
                    <div class="col-9">thitinan.p</div>
                </div>{{-- USER NAME --}}

                {{-- PASSWORD --}}
                <div class="row mt-2">
                    <div class="col-3"><b>PASSWORD : </b></div>
                    <div class="col-9">************* <a href="#">Change</a></div>
                </div>{{-- PASSWORD --}}

                {{-- PERMISSION --}}
                <div class="row mt-2">
                    <div class="col-3"><b>PERMISSION : </b></div>
                    <div class="col-9">Administrator</div>
                </div>{{-- PERMISSION --}}
            </div>
        </div>
        {{-- CONTENT --}}
        </div>
    </div>
</div>{{-- MAIN Backoffice --}}
@endsection

resources/views/backend/person.blade.php
@extends('layout.master_backend')

@section('contentBackoffice')
<!-- DataTables Example -->
<div class="card mb-3 main_font">
    <div class="card-header"><i class="fas fa-table"></i>{{ $topicPage }}</div>
    <div class="card-body">
        <div class="table-responsive">
<div align="right" class="mb-2">
    <a href="{{ route('addPerson') }}" class="btn btn-success btn-x active" role="button" aria-pressed="true">เพิ่มรายการ</a>
    <a href="#" class="btn btn-primary btn-x" role="button" aria-pressed="true">บันทึกข้อมูล</a>
    <a href="#" class="btn btn-secondary btn-x" role="button" aria-pressed="true">ลบรายการ</a>    
</div>
        
<table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
    <thead>
        <tr>
            <th>ชื่อ-นามสกุล</th>
            <th>ตำแหน่ง</th>
            <th>สถานะ</th>
            <th>EDIT</th>
            <th>DELETE</th>
            <th>Last Update</th>            
        </tr>
    </thead>
    <tfoot>
        <tr>
            <th>ชื่อ-นามสกุล</th>
            <th>ตำแหน่ง</th>
            <th>สถานะ</th>
            <th>EDIT</th>
            <th>DELETE</th>
            <th>Last Update</th>   
        </tr>
    </tfoot>
    <tbody>
    @foreach ($DataHisPerson as $arrDataHisPerson )            
        <tr>
            <td>
                {{ $arrDataHisPerson->title_name_th.$arrDataHisPerson->fname_th }}
                {{ $arrDataHisPerson->lname_th }}
            </td>
            <td>
                {{ $arrDataHisPerson->pos_counc_name_th }}
                ( {{ $arrDataHisPerson->delegate_year }} )
            </td>
            <td>{{ $arrDataHisPerson->person_status }}</td>
            <td><a href="{{ url('FrmEditPerson/'.$arrDataHisPerson->personID.'/edit') }}" class="btn btn-link">edit</a></td>
            <td>del</td>
            <td>2011/04/25</td>            
        </tr>                
    @endforeach        
    </tbody>        
</table>  

        </div>
    </div>    
</div>

@endsection